### ISSUE TITLE
error cillum

### ISSUE THREAD

**Issue by LastAM** [aenix-io/cozystack#273]
Использовал: https://www.youtube.com/watch?v=4k9KtSL4YBc&t=232s
Окружение: proxmox 8.2.4; talos 1.7.6; 

ошибка
$kubectl get hr -A
NAMESPACE                        NAME                        AGE    READY   STATUS
cozy-cert-manager                cert-manager                128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-cert-manager                cert-manager-issuers        128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-cilium                      cilium                      128m   False   HelmChart 'cozy-system/cozy-cilium-cilium' is not ready: no artifact 
.......
cozy-postgres-operator           postgres-operator           128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-rabbitmq-operator           rabbitmq-operator           128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-redis-operator              redis-operator              128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-telepresence                telepresence                128m   False   dependency 'cozy-cilium/cilium' is not ready
cozy-victoria-metrics-operator   victoria-metrics-operator   128m   False   dependency 'cozy-cilium/cilium' is not ready
tenant-root                      tenant-root                 128m   False   dependency 'cozy-cilium/cilium' is not ready

Talos:
![talos ](https://github.com/user-attachments/assets/4dd1cc24-d4be-4ef4-a5eb-125ae342a327)
![talos 2](https://github.com/user-attachments/assets/66fab048-832b-490a-b690-98f742f4547d)

**Comment by LastAM** [comment]
Find bug report on Talos: [https://github.com/siderolabs/talos/issues/9102](https://github.com/siderolabs/talos/issues/9102)

**Comment by SlavikCA** [comment]
У меня такая же ошибка.

Как это можно пофиксить?
