### ISSUE TITLE
Consider using cilium's native advertising over metallb?

### ISSUE THREAD

**Issue by danielloader** [aenix-io/cozystack#30]
Looks like a great project and just read about it on hacker news.

Cilium has a flag (beta admittedly) to do BGP advertisement itself - https://docs.cilium.io/en/stable/network/bgp-control-plane/

In addition to the l2 announcements - https://docs.cilium.io/en/stable/network/l2-announcements/#l2-announcements

Just wondering if there's scope to remove a component in the longer term.

Doing a great job and interested to see where the project goes!

**Comment by kvaps** [comment]
Heya! Thanks for idea!

We want to support both cilium and MetalLB, as well kube-ovn has [it's own implementation](https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/loadbalancer-service/) 

Unfortunately, we cannot deprecate MetalLB in favor of Cilium right now. Although this feature in Cilium is quite new, MetalLB currently holds advantages over Cilium's native advertising at this time. For instance, it still has some issues, such as the lack of support for `externalTrafficPolicy: Local`, see https://github.com/cilium/cilium/issues/27800#issuecomment-1698771543

Another advantage of MetalLB is [memberlist](https://metallb.universe.tf/concepts/layer2/#load-balancing-behavior). Unlike Cilium, which relies on Kubernetes' native leader election, MetalLB uses memberlist to enable IP failover even when the control plane is inaccessible

**Comment by danielloader** [comment]
Absolutely fantastic points! Thanks for the reply.
