### ISSUE TITLE
[etcd] Replace kamaji-etcd with etcd-operator

### ISSUE THREAD

**Issue by kvaps** [aenix-io/cozystack#33]
We initiated work on writing a new etcd-operator
https://github.com/aenix-io/etcd-operator/

We have to adopt it as soon it will be released

**Comment by nicklasfrahm** [comment]
Kamaji supports running on top of other datastores because it uses kine, would it not be easier to run it on top of CockroachDB?

**Comment by kvaps** [comment]
Hey, thanks for your idea!

Personally I have no much experience in CockroachDB as well in running Kubernetes with Postgres and any other SQL backends. At Ænix we have concerns about stability and scalability of this solution, so decided to use the most official method we can go and use etcd as the main backend for Kubernetes.

However we want to be extendable and support various methods in Cozystack, we just need to find who will sponsor or maintain the development of such configuration :)
