### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by matthieu-robin** [aenix-io/cozystack#344]
Users management and restriction per tenant

**Comment by kvaps** [comment]
Hi @matthieu-robin could you please describe which exactly permissions you want to manage using RBAC model?
It would be nice if you can provide user-story: "As Cozystack administrator I want to ..."

Initial design presumed that OIDC users and groups could be assigned per-tenant.
And in tenant-configuration you can define which applications with specific values could be deployed.

Would it be enough from your point of view?

**Comment by matthieu-robin** [comment]
As Cozystack administrator I want to ...
- Grant access to a final user only to his own tenant
- Create some roles ( read only, deploy, modify deployed app/service,...)
- Create users per tenant

Let me know if I'm not clear enough

**Comment by kvaps** [comment]
Very clear, thank you!
