### ISSUE TITLE
make build fail

### ISSUE THREAD

**Issue by RaSerge** [aenix-io/cozystack#350]
Hello!
On fresh clone v0.15.0 `make build` failed on   
```
67 | >>> RUN /tmp/buf lint ./cmd/kubeapps-apis
```
in `dashboard` image
![bug_2024-09-19_09-31](https://github.com/user-attachments/assets/6e49facc-fb80-4a42-99db-1ad9040f241b)

**Comment by RaSerge** [comment]
Excuse me, @kvaps, @gecube, is something wrong with my iissue? any feedback, please!

**Comment by kvaps** [comment]
Looks like some generic issue related only to kubeapps building script. Try removing lint logic from the kubeapps-apis Dockerfile:

https://github.com/aenix-io/cozystack/blob/620871a595694816eeb1a29a2bd4aba897f54d1f/packages/system/dashboard/images/kubeapps-apis/Dockerfile#L67

**Comment by RaSerge** [comment]
Thanks a lot!
