### ISSUE TITLE
Clickhouse backup and restore

### ISSUE THREAD

**Issue by tropnikovvl** [aenix-io/cozystack#369]
Hi!

You have a built-in data [backup](https://github.com/aenix-io/cozystack/blob/main/packages/apps/clickhouse/templates/backup-script.yaml) feature for ClickHouse. 
Could you tell me how consistent such a backup is? Is there a chance that, with large volumes of data, changes might be made and overwritten during the backup process? 

Also, I would like to clarify how the recovery process works.

Thank you.

**Comment by gecube** [comment]
@tropnikovvl Hi! Thanks for the question. What is the reason that you are asking? Do you need some specific warranties about data quality and integrity? I'd like to understand the use-case. Thanks in advance

**Comment by kvaps** [comment]
Clickhouse backup is done by simple saving tables and their data into restic on s3 

https://github.com/aenix-io/cozystack/blob/01ce122ada9b27a5b258a8de68d934ffb2297478/packages/apps/clickhouse/templates/backup-script.yaml#L29-L31

Data consistency is guaranteed at the table level.
Recovery is currently manual.

**Comment by tropnikovvl** [comment]
Thank you all for the responses! 

I'm asking to understand if there is a possibility of data loss during the backup process. Since Clickhouse doesn't have transactions, there could be a situation where partially changed data is backed up.

I just want to make sure that your approach is safe enough, because [this tool](https://github.com/Altinity/clickhouse-backup) also performs backups but in a slightly different way, and I'm trying to compare them.
