### ISSUE TITLE
Cillium doesn't start in distro-full bundle

### ISSUE THREAD

**Issue by myasnikovdaniil** [aenix-io/cozystack#383]
Hi
I've installed cozystack 0.15.0 with distro-full configuration.  
#### Problem 1 
Cillium doesn't start with default parameters because of error:
```
level=fatal msg="auto-direct-node-routes cannot be used with tunneling. Packets must be routed through the tunnel device." subsys=daemon
```
I don't understand why auto-direct-node-routes set to true, but it appears here 
```
packages/core/platform/bundles/distro-full.yaml
31:      autoDirectNodeRoutes: true
```
#### Problem 2
so I want to change this parameter via cozystack configmap, but it can't be done - merging `autoDirectNodeRoutes: true` from `distro-full.yaml` with custom parameter `autoDirectNodeRoutes: false` from `values-cilium` in cozystack configmap results in `autoDirectNodeRoutes: true` because this is [how merge function works](https://helm.sh/docs/chart_template_guide/function_list/#merge-mustmerge)

I will appreciate your answer for the question "why does it done like this"?

**Comment by kvaps** [comment]
Hmm, can you please `routingMode: native`?

**Comment by myasnikovdaniil** [comment]
Thank you, it works, cilium starts, pod to pod connectivity works

**Comment by kvaps** [comment]
Thank you for the report, this options will be enabled by default since the next release
