### ISSUE TITLE
Issue during upgrade from 0.16.2 to 0.16.3 : capi-provider

### ISSUE THREAD

**Issue by matthieu-robin** [aenix-io/cozystack#414]
Got an issue related to the capi-provider during the upgrade.
Hope it helps:

Helm rollback to previous release cozy-cluster-api/capi-providers.v9 with chart cozy-capi-providers@0.16.2 failed: cannot patch "kubeadm" with kind BootstrapProvider: Internal error occurred: failed calling webhook "vbootstrapprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.cozy-cluster-api.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-bootstrapprovider?timeout=10s": context deadline exceeded && cannot patch "kamaji" with kind ControlPlaneProvider: Internal error occurred: failed calling webhook "vcontrolplaneprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.cozy-cluster-api.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-controlplaneprovider?timeout=10s": context deadline exceeded && cannot patch "cluster-api" with kind CoreProvider: Internal error occurred: failed calling webhook "vcoreprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.cozy-cluster-api.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-coreprovider?timeout=10s": context deadline exceeded && cannot patch "kubevirt" with kind InfrastructureProvider: Internal error occurred: failed calling webhook "vinfrastructureprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.cozy-cluster-api.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-infrastructureprovider?timeout=10s": context deadline exceeded

**Comment by kvaps** [comment]
Thank you for report, could you please check the state of pods in cozy-cluster-api namespace:

```
kubectl get pod -o cozy-cluster-api
```

**Comment by kvaps** [comment]
All right, just found that fix for cluster api didn't work, I'm going to prepare a new release with https://github.com/aenix-io/cozystack/issues/414
